services:
  - type: web
    name: api-upload
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_SECRET_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET_NAME
        sync: false
      - key: CLOUDFLARE_R2_REGION
        sync: false
